### ISSUE TITLE
Explore possibility to extend functionality without adding to this repo

### ISSUE THREAD

**Issue by dragly** [CINPLA/expipe-plugin-cinpla#14]
This already has a lot of functionality and adding more requires changes to this repository which might break things for others. See if it is possible to extend the functionality of this repo (the same types etc) without actually changing code in this repo.

**Comment by lepmik** [comment]
All project specific functionality is to be put in own repositories, current repository will only maintain lab wide functionality such as transfer to database, register experiments etc.. Analysis, processing or registering which is project specific belongs in respective repositories. See https://github.com/CINPLA/septum-mec as an example.
