### ISSUE TITLE
Package missing in current linux-64 channels:    - expipe-plugin-cinpla

### ISSUE THREAD

**Issue by T-dogg** [CINPLA/expipe-plugin-cinpla#2]
conda install expipe expipe-cli expipe-browser exdir-cli exdir-browser expipe-io-neuro pyxona exana expipe-plugin-cinpla -c defaults -c cinpla/label/dev -c cinpla -c conda-forge
Fetching package metadata ...............

PackageNotFoundError: Package not found: '' Package missing in current linux-64 channels: 
  - expipe-plugin-cinpla

You can search for packages on anaconda.org with

    anaconda search -t conda expipe-plugin-cinpla

**Comment by lepmik** [comment]
expipe-plugin-cinpla er ikke på anaconda enda, se http://expipe-plugin-cinpla.readthedocs.io/en/latest/installation.html for installasjon.
