### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by malinroe** [CINPLA/expipe-plugin-cinpla#46]
I think it is supposed to be expipecli.utils and not expipe.cliutils in line 2 in expipe-plugin-cinpla\expipe_plugin_cinpla\cli\main.py and line 2 in expipe-plugin-cinpla\expipe_plugin_cinpla\imports.py?

**Comment by alejoe91** [comment]
HI @malinroe 

Does it throw an error? I think `expipe.cliutils` is correct (https://github.com/CINPLA/expipe/tree/master/expipe/cliutils)

You might need to `pip install --upgrade expipe`

**Comment by malinroe** [comment]
The browser-function gave an error on this, and I think I’ve updated everything, but the browser didn’t work until I changed it to expipecli.utils. I might still have a little mix between new and old repos, so that might have been the problem, but it works now that I changed it locally to expipecli, so I just wanted to ask.

**Comment by alejoe91** [comment]
do you have the `expipe-cli` package if you `pip list`?

**Comment by malinroe** [comment]
Yes, because I just updated the older version, I'm guessing it is not supposed to be there?
