### ISSUE TITLE
Not able to run display_browser due to other files than just recordings within the action folder

### ISSUE THREAD

**Issue by eliserolsen** [CINPLA/expipe-plugin-cinpla#62]
When running expipe_plugin_cinpla and opening the display_browser we get Keyerror: 'data'. Its expected that all folders in actions are recordings (containing a data folder with .nwb file), which is not always the case (i.e. "identify neurons" folder). Is it possible to make it skip action folders that do not have data?

**Comment by alejoe91** [comment]
Elise, can you share the entire error? Does it fail immediately or when you change to some specific tab?

**Comment by eliserolsen** [comment]
It fails immediately

![Error_display_browser](https://github.com/CINPLA/expipe-plugin-cinpla/assets/98153627/118608f9-2155-4346-8f02-681bb9a27c07)

**Comment by alejoe91** [comment]
Thanks! Will fix it by Friday

**Comment by alejoe91** [comment]
@eliserolsen can you try again on EduCloud?

Should be fixed!

**Comment by eliserolsen** [comment]
![image](https://github.com/CINPLA/expipe-plugin-cinpla/assets/98153627/5fb5a098-2041-4fc6-9526-141a6e86e9b6)

It looks like you have to give group permission again

**Comment by alejoe91** [comment]
mmm we did! @lepmik can you run the permission command one more time?

**Comment by alejoe91** [comment]
@eliserolsen can you paste the entire error?

**Comment by lepmik** [comment]
can you try now?

**Comment by eliserolsen** [comment]
I still get the same error. From what i can see it looks like Alessio is the one who has to give the permission for pycache
![image](https://github.com/CINPLA/expipe-plugin-cinpla/assets/98153627/899e1692-21fd-417e-b721-9b3488d4cb2d)

**Comment by alejoe91** [comment]
should be fixed now

**Comment by eliserolsen** [comment]
A new permission error.. 

![image](https://github.com/CINPLA/expipe-plugin-cinpla/assets/98153627/440672f9-223e-4275-b3b1-3c78b5aeffb6)


Checked the permission here:

![image](https://github.com/CINPLA/expipe-plugin-cinpla/assets/98153627/998b8474-bee9-41bd-9cc3-b8d7e60c47a4)

**Comment by alejoe91** [comment]
fixed again! Sorry about the back and forth!

**Comment by eliserolsen** [comment]
Great, the problem is fixed now!

**Comment by alejoe91** [comment]
closing then!
