### ISSUE TITLE
nwb conversion 

### ISSUE THREAD

**Issue by mariapfj** [CINPLA/expipe-plugin-cinpla#65]
when running the conversion script, I keep having issues with some but not all recordings. In the latest attempt, there are 18 action folders in the old project path,  of which 13 are completely ignored and 3  get the following error message: 
Source data is valid!
Attaching probe
Running conversion to NWB
Metadata is valid!
conversion_options is valid!
Error processing action 002-140721-3. Removing it from new project:
Error:
column 'channel' already exists in TimeIntervals 'trials'

so in the end I'm left with 2 successful conversions, 3 failures, and a lot of ignored action folders?

in case you want to check them out its
old_project_path = Path("/projects/ec109/maria/novel-env-exdir")
new_project_path = Path("/projects/ec109/maria/novel-env-nwb")

**Comment by alejoe91** [comment]
Can you give me access to `"/projects/ec109/maria/novel-env-exdir"`?

You can run: 
`"chgrp -R ec109-member-group /projects/ec109/maria/novel-env-exdir"`

This will give access to the entire group, but otherwise I'm not able to run it on my side. Is that ok?

**Comment by alejoe91** [comment]
Testing now :)

**Comment by alejoe91** [comment]
Ok, I was able to reproduce the issue.

In my case, though, 11 actions completed, and the other 7 failed for the issue you mentioned. Can you try to run it again on your side?

I'll fix the trial stuff on monday!

**Comment by alejoe91** [comment]
Ok it was actually a quick fix and it's done on EduCloud!

Here's the output of the conversion of your project on my side:
![image](https://github.com/CINPLA/expipe-plugin-cinpla/assets/17097257/6718c213-d702-4aa9-8ddb-7274c795b35d)

Only one action failed, and I suspect that the open ephys folder in the main.exdir has not been fully uploaded successfully.

Closing :)
