### ISSUE TITLE
First tetrode is always given when specifying channel_group

### ISSUE THREAD

**Issue by lepmik** [CINPLA/expipe-plugin-cinpla#69]
This took a long time to figure out! When loading with `channel_group='tetrode1'` I get the units from `tetrode0`
https://github.com/CINPLA/expipe-plugin-cinpla/blob/ebd4b0217ae51a79111482f5bc86822f87a3117b/src/expipe_plugin_cinpla/data_loader.py#L233

<img width="1017" alt="image" src="https://github.com/CINPLA/expipe-plugin-cinpla/assets/3418096/b20a8469-2acd-431b-80cb-f30d4489fd9e">

This is for `/projects/ec109/maria/novel-env-nwb/actions/001-140721-7/`

**Comment by alejoe91** [comment]
@lepmik we can close this right?

**Comment by lepmik** [comment]
yes

tir. 18. juni 2024 kl. 10:42 skrev Alessio Buccino ***@***.***
