### ISSUE TITLE
if one channel is grounded the relative channel group gets only one messy cluster

### ISSUE THREAD

**Issue by alejoe91** [CINPLA/expipe-plugin-cinpla#7]
We could duplicate one of the good channels in the channel group on the bad one

**Comment by espenhgn** [comment]
Wouldn't this screw up with klusta? Would it not be better to provide klusta with a modified probe file where the grounded channel is removed from the probe-file 'channel' entry? This works well when manually running klusta it seems.

**Comment by alejoe91** [comment]
I think the clustering would not be screwed up, as we are removing noisy information and just duplicating existing information. Sometimes EAP is a bad channel, but when filtered in the LFP band it might still be useful. Anyway we could discuss about modifying the probe file on the fly. It can be a good solution :)

**Comment by espenhgn** [comment]
Ok, maybe some middle ground would be fine. I suppose "bad" channels can be labeled as such in exdir/Neo when --ground is used in the process action, and that subsequent analysis using e.g., exana would raise some userWarning if that data is used.

**Comment by alejoe91** [comment]
Now this is nicely fixed by removing the bad channels in spike_extractors. Needs to be updated for the command line interface though

**Comment by alejoe91** [comment]
Fixed with SpikeInterface: bad channels are removed
