### ISSUE TITLE
Unit "number" in curation view in browser does not match phy unit ID

### ISSUE THREAD

**Issue by sarahthon** [CINPLA/expipe-plugin-cinpla#71]
Hi, two questions:

1) 
After curating in phy, the reloaded and curated units seen in the "curation" tab in the display browser do not match with the saved unit "ID" that is reported in phy. Making it very challenging to look at curated units in the display and comparing them to units in phy.

I eg, there no longer exists a unit in phy with ID "23" after curating. It seems like the unit ID in browser display is not updated (even after reloading units from phy:
![image](https://github.com/CINPLA/expipe-plugin-cinpla/assets/39300702/c6d4caa7-2898-4cb1-b626-a2226cb23846)

2)
Also, can we rather choose "phy unit ID"  in the tab (where the number 5 is listed in the picture above), instead of what seems to be a list of the total number of cells ( i.eg. 0,2...,20 for 21 cells instead of their phy-ID)?

**Comment by alejoe91** [comment]
Hi Sarah,

1. In Phy you should have a `si_unit_id` column which corresponds to the SpikeInterface unit id.
2. In the display, the dropdown displays the unit ID in the NWB file, which is an index (so it's always between 0 and N-1).

Since there are multiple ways to curate, there is no guarantee that the "phy unit ID" is available (e.g. when using quality metrics)

**Comment by sarahthon** [comment]
1. This goes missing during curation (see picture). I thought maybe the "Id" option would be more stable. 
![image](https://github.com/CINPLA/expipe-plugin-cinpla/assets/39300702/e388283d-e601-4551-a5d9-116a9d49e5b2)

2. I see - I can work with it "as is" :)

**Comment by alejoe91** [comment]
I see! You can also check the unit table in the NWBViewer (open the Units and got to `table`, there should be a column called `original_cluster_id` :)

Alternatively, in a different cell, you can read the sorting object and print this `original_cluster_id` as follows:
```
import spikeinterface.extractors as se

sorting_phy = se.read_phy("path-to-phy-folder") 
# you can copy past it from the GUI (after `phy template-gui`)
# note that you have to remove the params.py from the file path

print(sorting_phy.get_property("original_cluster_id"))
```

**Comment by sarahthon** [comment]
Its probably hidden here, should I be able to click on it to expand(does not work now)?
![image](https://github.com/CINPLA/expipe-plugin-cinpla/assets/39300702/77e8280e-feec-4f47-9052-e444e3cb4d59)

**Comment by sarahthon** [comment]
I assume it is updated form the "summary" tab somehow, trying to figure out how to update it according to my choices

**Comment by alejoe91** [comment]
Not sure if you can expand...can you try by loading directly the SpikeInterface Sorting object?

**Comment by sarahthon** [comment]
I get all the units (including noise), how can I exclude units marked as "noise"? 


I eg, I have 21 units marked as unsorted, good or mua, but the output here lists all phy units (including 41 noise "units"):
![image](https://github.com/CINPLA/expipe-plugin-cinpla/assets/39300702/707e619b-eeeb-4566-bdfc-ac6665efd98e)


Still I would have to match to the correct unit in phy, which I guess can be done manually when I sort on increasing unit ID number. But not the optimal solution when having many units

**Comment by alejoe91** [comment]
You can simply do this!

`sorting_phy = se.read_phy("path-to-phy-folder", exclude_cluster_groups=["noise"])`

**Comment by alejoe91** [comment]
@sarahthon can we close this?

**Comment by sarahthon** [comment]
Hi again, I see that when we use "save as NWB Units" in the display browser, it continues to store units with the ID that appears in "curation" rather than the unit "id" from phy. Can you update so that it saves curated units with phy id instead? It is very time consuming to use the other solution discussed here. I need to directly compare units in later notebooks to units in phy. 

Best, Sarah

**Comment by alejoe91** [comment]
Hi @sarahthon 

The NWB conversion (external package) code will save unit ids in ascending order. I'll see if it's possible to override these, but I don't think it is. 

You still have the `original_cluster_id` column with the Phy unit ids, right?

**Comment by sarahthon** [comment]
I didn't find it previously, but now I find it in the unit table in the NWBViewer 👍 

If these are stored in the saved "curated NWB units", then we should be able to fetch these when working in later notebooks?

**Comment by alejoe91** [comment]
so currently these are saved to the NWB units as "original_cluster_id"! 

You can use this to fetch it:

```
sorting = se.read_nwb_sorting("path-to-nwb-file", electrical_series_path="acquisition/ElectricalSeries")

original_cluster_ids = sorting.get_property("original_cluster_id")
```

Let me know if it works

**Comment by sarahthon** [comment]
I am not able to find the correct path. I also tested out pointing to "/projects/ec109/Sarah/projects/hpc-social-nwb/actions/001-211220-1/data", with no luck.
![image](https://github.com/user-attachments/assets/28007594-4f61-4db6-99f9-2291b23312ed)
 
- Sarah

**Comment by alejoe91** [comment]
You need the path to the nwb file, not Phy! Should be .../data/main.nwb
