### ISSUE TITLE
can't register new actions

### ISSUE THREAD

**Issue by sarahthon** [CINPLA/expipe-plugin-cinpla#75]
Hi, suddenly I am receiving this error when registering a recording from open ephys:

![image](https://github.com/CINPLA/expipe-plugin-cinpla/assets/39300702/19897294-ead0-4ca7-825b-6fe20aa8de99)
![image](https://github.com/CINPLA/expipe-plugin-cinpla/assets/39300702/1baf74bf-7aa7-40c2-8a3b-87a921b57b27)
![image](https://github.com/CINPLA/expipe-plugin-cinpla/assets/39300702/afa7cdd0-9070-4743-a9d1-b06cb79140fa)
![image](https://github.com/CINPLA/expipe-plugin-cinpla/assets/39300702/a6896793-1f6b-4903-a14f-0e394f99e620)
![image](https://github.com/CINPLA/expipe-plugin-cinpla/assets/39300702/2147c22d-9871-46c2-abad-b339c241962d)
![image](https://github.com/CINPLA/expipe-plugin-cinpla/assets/39300702/3db41d92-9c03-4e87-84da-084e9ec6c43f)

In the "continuous" folder, there should only be the "Rhythm_FPGA-100.0" folder. 
Could the error be related to an update?

my paths should be correct: 
/projects/ec109/Sarah/Rådata/002_2020-12-12_11-58-24_1
probe path:
/projects/ec109/Sarah/projects/tetrode_32_openephys.json

- Sarah

**Comment by sarahthon** [comment]
Not that I can think of. I have recorded some filtered signal, which I think ended up as an additional folder in this folder (that I later removed because the files became unnecessarily large), but that was at a late time, not for this recording. I did manage to register it locally (but I can't spikesort locally so I have to do this on educloud).

**Comment by sarahthon** [comment]
But I am able to register recording '007_2021-12-08_16-21-09_1', so the problem seems specific to this recording and maybe not the plugin.

**Comment by alejoe91** [comment]
What is the content of the `continuous` folder?

**Comment by alejoe91** [comment]
Not this one, the parent folder

**Comment by sarahthon** [comment]
only the 'Rhytm_FPGA-100.0' folder:
![image](https://github.com/CINPLA/expipe-plugin-cinpla/assets/39300702/ccebbddc-5981-4ef0-b521-008b0e42c2ee)

**Comment by alejoe91** [comment]
Ok, not sure then why it's looking for the other folder. Can you send me this dataset?

**Comment by alejoe91** [comment]
@sarahthon this is fixed after changing the settings.xml right? can we close?

**Comment by sarahthon** [comment]
Yes, it works now with the fixing in settings. Thanks!
