### ISSUE TITLE
various error messages seemingly related to data_loader and data_processing

### ISSUE THREAD

**Issue by mariapfj** [CINPLA/expipe-plugin-cinpla#76]
issues with identify-neurons and plot-sessions resolved

**Comment by sarahthon** [comment]
In my case it seems that the sys.path.append doesn't work, it struggles with everything after this line:
![image](https://github.com/CINPLA/expipe-plugin-cinpla/assets/39300702/657739d4-9e9f-457a-af7b-759c17ecdde3)
![image](https://github.com/CINPLA/expipe-plugin-cinpla/assets/39300702/5091c2d5-02ce-4e64-b29e-d8fe640d422f)
