### ISSUE TITLE
Spikesorting failing - temporary folders not deleted in kernel?

### ISSUE THREAD

**Issue by sarahthon** [CINPLA/expipe-plugin-cinpla#82]
Getting errors with temporary folders for several actions that I try to spikesort, Can you help me out? Hope it's not a problem with the raw data. 

![image](https://github.com/user-attachments/assets/a78158de-7ec9-4d1b-911a-91a68e8be07f)

Sarah

**Comment by alejoe91** [comment]
Hi @sarahthon 

Have you sorted these dataset before?

**Comment by sarahthon** [comment]
The datasets were not previously spikesorted, but when re-spikesorting on the new kernel-update I had to manually remove the spikeinterface-folder and now it works! Thanks!
