### ISSUE TITLE
mixup in units?

### ISSUE THREAD

**Issue by mariapfj** [CINPLA/expipe-plugin-cinpla#87]
Ref issue posted recently with removing excess spikes; was able to spikesort 137-310121-7 from mec-social but I'm encountering some really odd issues during curation. 

One unit (really nice grid cell so can't simply ignore it) seems to have been merged across tetrodes, only to be revealed as belonging to separate tetrodes when clustercutting. Images shows units 135 and 136, which I split from a single unit initially. However out of nowhere the amplitude and main channel changes (from 28 to 18 for one unit, not the other), as well as waveforms (clearly showing two different tetrodes). channel_group remains the same for both (contrary to changes in ch), but if I keep curating, or undo changes, channel_group disappears (this has previously also been an issue when saving to nwb, can't remember if we implemented a solution already). 

I have no idea whats going on here
 
![image](https://github.com/user-attachments/assets/dce29a5c-3922-4d3e-8c69-c67fd87b4eb4)
![image](https://github.com/user-attachments/assets/89c9adbe-9c7d-40a7-8a54-7adb21fcbc65)

this is what is seen in the notebook before I start clustercutting, before it splits into two different units, which seems to correpsond more to the "noisy" unit in phy (ref a missing channel), but also the waveform corresponds a lot better to what the unit initially looks like before I start clustercutting

![image](https://github.com/user-attachments/assets/09897e9c-56cb-44e3-9fb6-23d71daa6e13)
![image](https://github.com/user-attachments/assets/2f90e82c-ad4c-4264-98aa-e7bb0a152074)

**Comment by mariapfj** [comment]
can also add that they have a similarity score of 1 :)

**Comment by mariapfj** [comment]
for reference this is what it looks like initially, before removing anything

![image](https://github.com/user-attachments/assets/ba8afb15-0371-4d8e-9c59-a3ea1e27c5fc)

**Comment by alejoe91** [comment]
So that seems to be a problem with Phy?

**Comment by mariapfj** [comment]
phy or kilosort i guess, but i wanted to run it by you in case it could be
related to any changes made recently ?

fre. 20. sep. 2024 kl. 16:55 skrev Alessio Buccino ***@***.***

**Comment by alejoe91** [comment]
I see! It could be that those spikes that you're cutting out because they look lilke outliers on in the feature view are indeed noisy spikes that also appear on other channels. This means that by isolating them into a separate cluster, the main signal could be associated to a different tetrode. Does it make sense?

**Comment by mariapfj** [comment]
could be yeah, I’ll have another look on monday to see if I can sort it out

fre. 20. sep. 2024 kl. 17:08 skrev Alessio Buccino ***@***.***
