### ISSUE TITLE
failed registration of raw data that are "missing" folders

### ISSUE THREAD

**Issue by sarahthon** [CINPLA/expipe-plugin-cinpla#90]
Hi, I am receiving an error because of a folder I deleted in the raw data recording, but expipe still expects it to be there. Can you allow "Channel_Map-101_100.0" to be skipped when it is not present in the folder 'projects\ec109\Sarah\Rådata_HPC\002_2020-12-13_14-58-59_1\experiment1\recording1\continuous'? 

(I recorded from Channel_Map in addition to FPGA but it doubled the size of the recordings, and we don't use it so I deleted it to avoid 20 GB action folders..) 

![image](https://github.com/user-attachments/assets/cafda3f8-12b0-4f8b-ab22-6ec13e511f6f)
![image](https://github.com/user-attachments/assets/7694bcde-ad6a-4fe7-8ae1-4808c8959270)
![image](https://github.com/user-attachments/assets/e127b27a-cb04-480a-bef3-1ef083328797)
![image](https://github.com/user-attachments/assets/a8dc4139-9518-49f5-8237-f93f7f7ffba9)
![image](https://github.com/user-attachments/assets/be5abdc9-e13b-4fd9-8ed8-49b566cc7a56)
![image](https://github.com/user-attachments/assets/ad9b2234-7bd3-4e05-9e4b-380f2c826e4e)

Best, Sarah

**Comment by alejoe91** [comment]
Hi Sarah, unfortunately you can't delete a folder, because a bunch of other metadata would point to it and this is causing the issue.

The only way to recover the session is to modify the structure.oebin and remove the Channel_Map section

**Comment by sarahthon** [comment]
Unfortunately I was not aware that expipe registration depended on this at that time, as we just wanted to include ch_map for other analysis. However this was not for many recordings and after a second attempt at editing the structure.oebin file I managed to remove the right section. :)
